import { LeadMagnet } from '@prisma/client'

export const DEFAULT_LEAD_MAGNET: LeadMagnet = {
  name: 'New Lead Magnet',
  status: 'draft',
  draftBody: '',
  draftTitle: '',
  draftSubtitle: '',
  draftPrompt: '',
  draftEmailCapture: '',
  draftFirstQuestion: '',
  publishedBody: '',
  publishedEmailCapture: '',
  publishedFirstQuestion: '',
  publishedPrompt: '',
  publishedSubtitle: '',
  publishedTitle: '',
  createdAt: new Date(),
  updatedAt: new Date(),
  publishedAt: null,
  slug: '',
  pageViews: 0,
  id: '',
  userId: '',
}
